### ISSUE TITLE
Should it be possible to check the license of another application?

### ISSUE THREAD

**Issue by ComLock** [enonic/lib-license#21]
app-explorer (private github repo) is licensed https://github.com/enonic/app-explorer/blob/master/src/main/resources/app.pub

Installing and checking a license works fine within app-explorer.

However when I check the license inside a Collector app things fail.
https://github.com/enonic/lib-explorer/blob/master/src/main/resources/lib/explorer/collector/Collector.es#L46

Imported here:
https://github.com/enonic/app-explorer-collector-surgeon/blob/master/src/main/resources/tasks/collect/collect.es#L7

People are supposed to make their own collectors, and we can't give'em the app.pub file.
So for now I think I'll have to drop the backend license checks...

**Comment by alansemenov** [comment]
@ComLock why is this a task and not a question on Slack?

**Comment by ComLock** [comment]
I think I talked about this with you. And @sigdestad wasn't around. So I made this issue for him to answer it. I guess slack could have worked too.

**Comment by sigdestad** [comment]
AFAIK, there is no such thing as a license for an application. There is a license with a specific identifier, and any app can check for any license.

**Comment by ComLock** [comment]
There is a public and a private key. So I guess even though a collector app doesn't have the private key. It should be possible to check installed license based on the application name of the main explorer application.

**Comment by sigdestad** [comment]
Not sure I'm getting your question. We have a single license that is supposed to work across all our applications. But in order to validate, I guess the application will need to have the public key in the code, and that the private key is the one uploaded to XP?

**Comment by ComLock** [comment]
app-explorer has private key, and after installation of public key, validation works
app-collector-whatever via lib-explorer does not have private key, but still want to validate license before running collect task.

One solution is to add public key to lib-explorer, but I think it should be possible to validate a installed license even without that. It just that I didn't think of it at the time and was somewhat confused by the documentation.

**Comment by sigdestad** [comment]
Ah.. Key probably needs to be in lib then.

**Comment by ComLock** [comment]
Ok. That means this issue can be closed.
